stages:
  - tests (C++14) -- cppcheck, build (linux, gcc5), tests

jobs:
  include:
     - stage: tests (C++14) -- cppcheck, build (linux, gcc5), tests
       sudo: required
       dist: trusty
       language: cpp
       compiler: g++
       os: linux
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
             - g++-5
             - cppcheck
       before_install:
         - pip install --user cpp-coveralls
       install: export CXX="g++-5"
       script:
         - set -e

         - cmake -Bbuild -H. -DUNIT-TESTS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DCOVERAGE:BOOL=ON

         - cppcheck --enable=all -I include -I test-utils/include -I tests/unit/include --language=c++ --platform=unix64 --std=c++11 --check-config --suppress=missingIncludeSystem -v ./tests

         - cmake --build build --target run-all-tests-verbose --config RelWithDebInfo
         - coveralls -e ./build/gtest-src -e ./build/CMakeFiles -e ./tests/unit -e cmake-helpers -e test-utils --gcov-options '\-lp'

         - set +e
